### PR TITLE
Add frontend and backend

### PR DESCRIPTION
**Pull request by mukundkumra**

### CODE REVIEW

**Comment by romio-appsimity** [comment]
Few things missing in the app:
1. User should have an option to edit the task.
2. User should have option to view their completed tasks.
3. User should be able to view their own tasks.(Each task should be associate with an user)

Please complete the above functionality and let me know. Thanks

**Comment by mukundkumra** [comment]
Sir, I have made the following changes you requested:

1. Edit functionality for tasks
2. Option to view completed task.
3. User Authentication and personalised task list for each user.

**Comment by romio-appsimity** [comment]
Still some issues appears on the app. Please fix the following issues:

**Frontend:**

- Unnecessary API call: **GET /api/tasks/nileshuber@gmail.com 304**  **(Infinite times)**
- React hooks are not configured correctly
- System allowing me to create a task without typing a single character(It should prompt "You have to enter at-least one character to create a task")  

Screenshots:
image
image

**Backend:**

- Instead of storing completed tasks in different collection, add an additional "status" field(e.g. todo, completed, pending as status ) on tasks schema and then filter data based on the status.

For any query feel free to contact me.

Thanks:)

**Comment by mukundkumra** [comment]
Sir, I've made the changes you requested, hopefully it is as per your requirements

**Comment by romio-appsimity** [comment]
Almost everything functioning properly except page refreshing issue.

**Pull request merged**
